'use server';
/**
 * @fileOverview An AI agent that generates compelling event descriptions for event organizers.
 *
 * - generateEventDescription - A function that generates event descriptions.
 * - GenerateEventDescriptionInput - The input type for the generateEventDescription function.
 * - GenerateEventDescriptionOutput - The return type for the generateEventDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEventDescriptionInputSchema = z.object({
  eventName: z.string().describe('The name of the event.'),
  eventCategory: z.string().describe('The category of the event (e.g., business, technology, art).'),
  targetAudience: z.string().describe('The target audience for the event (e.g., female entrepreneurs, tech professionals, artists).'),
  eventDate: z.string().describe('The date of the event.'),
  eventTime: z.string().describe('The time of the event.'),
  eventLocation: z.string().describe('The location of the event.'),
  eventDescriptionKeywords: z.string().describe('Keywords related to the event to highlight in the description.'),
});
export type GenerateEventDescriptionInput = z.infer<typeof GenerateEventDescriptionInputSchema>;

const GenerateEventDescriptionOutputSchema = z.object({
  eventDescription: z.string().describe('A compelling event description generated by the AI.'),
});
export type GenerateEventDescriptionOutput = z.infer<typeof GenerateEventDescriptionOutputSchema>;

export async function generateEventDescription(input: GenerateEventDescriptionInput): Promise<GenerateEventDescriptionOutput> {
  return generateEventDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEventDescriptionPrompt',
  input: {schema: GenerateEventDescriptionInputSchema},
  output: {schema: GenerateEventDescriptionOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in creating compelling event descriptions.

  Using the information provided below, generate an engaging event description to attract more attendees.

  Event Name: {{{eventName}}}
  Event Category: {{{eventCategory}}}
  Target Audience: {{{targetAudience}}}
  Event Date: {{{eventDate}}}
  Event Time: {{{eventTime}}}
  Event Location: {{{eventLocation}}}
  Event Description Keywords: {{{eventDescriptionKeywords}}}

  Write a description that is concise, engaging, and highlights the key benefits of attending the event. Make it sound like it is targeted at female entrepreneurs.
  `,
});

const generateEventDescriptionFlow = ai.defineFlow(
  {
    name: 'generateEventDescriptionFlow',
    inputSchema: GenerateEventDescriptionInputSchema,
    outputSchema: GenerateEventDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
